# Generated by Django 2.1.10 on 2019-07-10 05:40

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
