# Generated by Django 2.1.10 on 2019-07-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='image_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
