# Generated by Django 2.1.5 on 2019-03-23 01:50

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_basepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basepage',
            name='content',
        ),
        migrations.AddField(
            model_name='basepage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(help_text='lsknlknflknlas dlajs lajs lajs f')), ('align', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center'), ('justify', 'Justify')]))]))], default=''),
            preserve_default=False,
        ),
    ]
