# Generated by Django 2.1.10 on 2019-07-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_links_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='image_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
