# Generated by Django 2.2.5 on 2019-10-28 09:22

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_learncategory_learncontentpage_learnpagelearncategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(help_text='Add your text in here')), ('align', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center'), ('justify', 'Justify')]))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(help_text='Add your text in here')), ('align', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center'), ('justify', 'Justify')]))])), ('links', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add your title', required=True)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(help_text='If your page does not have both an image and a description it will not show up!', page_type=['home.BasePage'])))])), ('map', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Enter the title of the map')), ('location_lat', wagtail.blocks.DecimalBlock(max_digits=15, max_value=90, min_value=-90)), ('location_long', wagtail.blocks.DecimalBlock(max_digits=15, max_value=180, min_value=-180)), ('zoom', wagtail.blocks.DecimalBlock(max_value=21, min_value=0))]))]),
        ),
        migrations.AlterField(
            model_name='learncontentpage',
            name='body',
            field=wagtail.fields.StreamField([('categories', wagtail.blocks.StructBlock([('category_type', wagtail.blocks.CharBlock(help_text='Add your category type', required=False)), ('categories', wagtail.snippets.blocks.SnippetChooserBlock('home.LearnCategory', required=False))], blank=True, dafault='', null=True)), ('content', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(help_text='Add your content in here', required=False)), ('align', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center'), ('justify', 'Justify')]))], blank=True, null=True)), ('code', wagtail.blocks.StructBlock([('code', wagtail.blocks.StructBlock([('language', wagtail.blocks.ChoiceBlock(choices=[('css', 'CSS'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.blocks.TextBlock(identifier='code', label='Code'))], label='Bash Code', language='WAGTAIL_CODE_BLOCK_LANGUAGES', required=False)), ('align', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center'), ('justify', 'Justify')]))], blank=True, null=True))]),
        ),
        migrations.AlterField(
            model_name='learnpagelearncategory',
            name='learn_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.LearnCategory'),
        ),
        migrations.AlterField(
            model_name='learnpagelearncategory',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='home.LearnContentPage'),
        ),
    ]
