# Generated by Django 2.2.5 on 2020-02-11 14:41

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200117_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learncontentpage',
            name='body',
            field=wagtail.fields.StreamField([('Pages', wagtail.blocks.StructBlock([('languages', wagtail.blocks.ChoiceBlock(choices=[('tet', 'Tetum'), ('en', 'English')])), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(help_text='Add your page in here', page_type=['home.SubLearnContentPage'])))], blank=True, null=True))]),
        ),
    ]
