# Generated by Django 2.2.5 on 2019-12-26 23:54

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20191226_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learncontentpage',
            name='body',
            field=wagtail.core.fields.StreamField([('Pages', wagtail.core.blocks.StructBlock([('pages', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(help_text='Add your page in here', page_type=['home.SubLearnContentPage'])))], blank=True, null=True))]),
        ),
        migrations.AlterField(
            model_name='sublearncontentpage',
            name='body',
            field=wagtail.core.fields.StreamField([('category_type', wagtail.core.blocks.StructBlock([('category_type', wagtail.snippets.blocks.SnippetChooserBlock('home.LearnCategory_type', required=False)), ('align', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center'), ('justify', 'Justify')]))], blank=True, null=True)), ('content', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(help_text='Add your content in here', required=False)), ('align', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center'), ('justify', 'Justify')]))], blank=True, null=True)), ('code', wagtail.core.blocks.StructBlock([('code_url', wagtail.core.blocks.URLBlock(label='External URL', required=False)), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('css', 'CSS'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))], label='Source Code', language='WAGTAIL_CODE_BLOCK_LANGUAGES', required=False)), ('align', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center'), ('justify', 'Justify')]))], blank=True, null=True)), ('table', wagtail.core.blocks.StreamBlock([('table', wagtail.contrib.table_block.blocks.TableBlock()), ('align', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center'), ('justify', 'Justify')]))], blank=True, null=True))]),
        ),
    ]
